export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILURE = 'SET_INGREDIENTS_FAILURE'

export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILURE = 'PURCHASE_ORDER_FAILURE';
export const PURCHASE_ORDER_LOADING = 'PURCHASE_ORDER_LOADING';
export const PURCHASED_ORDER = 'PURCHASED_ORDER';

export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';
export const FETCH_ORDER_LOADING = 'FETCH_ORDER_LOADING';